#!/bin/sh
set -e

cd `dirname $0`

rev=`git rev-parse HEAD`

git pull
subs=`git submodule update --recursive`

if [ $rev != `git rev-parse HEAD` -o "x$subs" != "x" ] ; then
    cpanm --local-lib extlib local::lib
    cpanm --local-lib extlib --installdeps --notest .
    echo Restarting...
    ./alicectl stop
    ./alicectl start
fi
